# Generated by Django 5.2 on 2025-04-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('suhu', models.CharField(max_length=10)),
                ('kelembaban', models.CharField(max_length=10)),
                ('co2', models.CharField(max_length=20)),
                ('gas_lpg', models.CharField(max_length=20)),
                ('gas_alkohol', models.CharField(max_length=20)),
                ('cahaya', models.CharField(max_length=20)),
                ('jumlah_orang', models.IntegerField()),
                ('kebisingan', models.CharField(max_length=10)),
                ('tegangan', models.CharField(max_length=20)),
                ('arus', models.CharField(max_length=20)),
                ('daya', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='sensor',
        ),
    ]
